version: '3'
services:
  python-script:
    container_name: notoric-snc
    build: .
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=notoric-snc
      - GROQ_API_KEY=
      - OPENWEATHERMAP_API_KEY=
      - OPENWEATHERMAP_CITY=London,uk
      - NEWSAPI_API_KEY=
      - NEWSAPI_COUNTRY=gb
      - ARTICLE_LIFETIME=6 # in hours
      - ARTICLE_INTERVAL=1 # in hours
  mongodb:
    container_name: notoric-snc-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db